name: Exploring Secrets 

on: 
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: asset 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build 
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest 

    - name: Docker Login
      run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish 
      run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    concurrency:
      group: prod-deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run 
      run: |
        echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        sleep 600s