name: My-WorkFlow

on: push 

jobs:
  first_job:
    runs-on: ubuntu:latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List and Read File
      run: |
        echo "Github Actions - Redo"
        ls -ltra
        cat README.md 

    - name: Gen ASCII 
      run: cowsay -f dragon "Run for Github"