name: second-example

on: push

jobs:
  practice-curl:
    runs-on: ubuntu-latest
    steps:
    - name: install curl 
      run: sudo apt-get install curl 

    - name: enable nginx
      run: sudo systemctl start nginx.service


    - name: curl nginx
      run: curl http://localhost:80/ 


