name: second-example

on: push

jobs:
  practice-curl:
    runs-on: ubuntu-latest
    steps:
    - name: install curl 
      run: sudo apt-get install curl 

    - name: install nginx
      run: sudo apt-get install nginx

    - name: curl nginx
      run: curl localhost:80 


